### ISSUE TITLE
Is this project deprecated?

### ISSUE THREAD

**Issue by Sly777** [gkouziik/eslint-plugin-security-node#67]
Hey @gkouziik, I saw that there are some PRs that could be very important and some bugs related to the new eslint. Is this project deprecated/dead? If it's, I would like to contribute this to the public.

**Comment by gkouziik** [comment]
@Sly777 Hey due to some issues I left the repo without maintenance the past year. 
My goal is to update everything and review the issues and open PRs , starting from tomorrow since it has some legit weekly downloads. 
i am looking for some help due to lack of free time if you re available we can discuss any possible contributions

**Comment by gkouziik** [comment]
Hello @Sly777 ,
this project is still alive fyi
